fix composer installer

diff --git a/setup/docker/wordpress/Dockerfile b/setup/docker/wordpress/Dockerfile
--- a/setup/docker/wordpress/Dockerfile
+++ b/setup/docker/wordpress/Dockerfile
@@ -26,9 +26,15 @@ RUN apt-get install -y \
 ;
 
 # install composer
-RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
-    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'c5b9b6d368201a9db6f74e2611495f369991b72d9c8cbd3ffbc63edff210eb73d46ffbfce88669ad33695ef77dc76976') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
-    && php composer-setup.php \
-    && php -r "unlink('composer-setup.php');" \
+RUN EXPECTED_CHECKSUM="$(curl -Ls https://composer.github.io/installer.sig)" \
+    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+    && ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" \
+    && if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then \
+        >&2 echo 'ERROR: Invalid installer checksum' \
+        rm composer-setup.php \
+        && exit 1; \
+    fi \
+    && php composer-setup.php --quiet \
+    && rm composer-setup.php \
     && mv composer.phar /usr/local/bin/composer \
 ;
